kind: pipeline
type: docker
name: backend

steps:
- name: build
  image: golang:1.15
  commands:
  - go build
  - go test -v
  
- name: node
  image: node:14
  commands:
  - npm install
  - npm run test
