kind: pipeline
type: docker
name: backend

steps:
- name: build
  image: golang:1.15
  commands:
  - go build
  - go test -v
  when:
    event:
      include:
      - push
      - pull_request
  
- name: test
  image: golang:1.15
  commands:
  - go build
  - go test -v
  when:
    branch:
    - master
  
  
---
  
kind: pipeline
type: docker
name: frontend 

steps:
- name: node
  image: node:14
  commands:
  - npm install
  - npm run test
  
- name: paul_maven
  image: maven:3.6.3-jdk-11
  commands:
  - mvn package
  
- name: notify
  image: drillster/drone-email
  settings:
    host: ivoss.com
    skip_verify: true
    username: harness@ivoss.com
    password:
      from_secret: alex_smtp_pw
    from: harness@ivoss.com
    recipients: [ paul.suholet@harness.io, psuholet@gmail.com ]
  when:
    status: [ success, changed, failure ]
    branch:
      -master
  
services:
- name: redis
  image: redis:6
  
  
